_wandb:
    value:
        cli_version: 0.25.1
        e:
            2fxlclgvsl3qp8pmpp3z0zvikwvajk1a:
                args:
                    - 0flch31g
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1999375429632"
                        used: "990422691840"
                email: willemvd@outlook.com
                executable: C:\Users\Wille\anaconda3\envs\trackmania-rl\python.exe
                git:
                    commit: a909928e0da2b4bc0a0c007829c78957a156cdc5
                    remote: https://github.com/Tizianovdzwet/Autonomous-systems-Portfolio.git
                host: Willem_PC
                memory:
                    total: "33409187840"
                os: Windows-10-10.0.26200-SP0
                program: -m src.sweep
                python: CPython 3.10.20
                root: C:\Users\Wille\OneDrive - De Haagse Hogeschool\Documenten\GitHub\Autonomous-systems-Portfolio\Portfolio 2
                startedAt: "2026-05-14T10:47:49.408053Z"
                writerId: 2fxlclgvsl3qp8pmpp3z0zvikwvajk1a
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.10.20
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
batch_size:
    value: 16
epsilon_decay:
    value: 0.99
gamma:
    value: 0.95
hidden_size:
    value: 32
lr:
    value: 0.001
