_wandb:
    value:
        cli_version: 0.26.1
        e:
            gugb2zvl48tyav3d46yabj6gt94g8ae7:
                args:
                    - 69gnvced
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "510769754112"
                        used: "399928684544"
                email: matthias@devreede.net
                executable: C:\Users\matth\miniconda3\envs\trackmania\python.exe
                git:
                    commit: 3c837a7c67b81f76cf8c95f75b59f71cb779f39a
                    remote: https://github.com/Tizianovdzwet/Autonomous-systems-Portfolio.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-14255b5d-2007-b415-1a63-bb8880f20b6f
                host: TIES-LEGION
                memory:
                    total: "16505966592"
                os: Windows-10-10.0.26200-SP0
                program: -m src.sweep_phase_2
                python: CPython 3.10.20
                root: C:\Users\matth\Autonomous-systems-Portfolio\Portfolio 2
                startedAt: "2026-05-15T11:16:31.536445Z"
                writerId: gugb2zvl48tyav3d46yabj6gt94g8ae7
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
                - 17
                - 61
            "4": 3.10.20
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
batch_size:
    value: 32
episodes:
    value: 1000
epsilon_decay:
    value: 0.999
gamma:
    value: 0.99
hidden_size:
    value: 64
lr:
    value: 5e-05
resume_command:
    value: python -m src.sweep2 69gnvced
run_name:
    value: p2-lr5e-05-decay0.999-gamma0.99-tgt50
target_update_every:
    value: 50
train_every:
    value: 16
