_wandb:
    value:
        cli_version: 0.26.1
        e:
            bs45bnk769dn3xl7ap0makkodhj7de5p:
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "499429404672"
                        used: "435115380736"
                email: matthias@devreede.net
                executable: C:\Users\matt\miniconda3\envs\trackmania\python.exe
                git:
                    commit: 37f78876088b857ba14f55c0375275b6f31096c4
                    remote: https://github.com/Tizianovdzwet/Autonomous-systems-Portfolio.git
                gpu: NVIDIA GeForce RTX 4070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 5888
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070
                      uuid: GPU-a0db4fb5-d0e2-b7b1-f0a0-247ce864b901
                host: DESKTOP-V93H26C
                memory:
                    total: "34262204416"
                os: Windows-10-10.0.19045-SP0
                program: -m src.baseline.random_policy
                python: CPython 3.10.20
                root: C:\Users\matt\Documents\[1] - Code Projects\[0] - College\Autonomous-systems-Portfolio\Portfolio 2
                startedAt: "2026-05-13T19:31:19.574112Z"
                writerId: bs45bnk769dn3xl7ap0makkodhj7de5p
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.20
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
episodes:
    value: 10
policy:
    value: random
