_wandb:
    value:
        cli_version: 0.26.1
        e:
            v79d8dso9xzjm0vm7oo3927n6p957rdk:
                args:
                    - 0flch31g
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "510769754112"
                        used: "403410624512"
                email: matthias@devreede.net
                executable: C:\Users\matth\miniconda3\envs\trackmania\python.exe
                git:
                    commit: a909928e0da2b4bc0a0c007829c78957a156cdc5
                    remote: https://github.com/Tizianovdzwet/Autonomous-systems-Portfolio.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-14255b5d-2007-b415-1a63-bb8880f20b6f
                host: TIES-LEGION
                memory:
                    total: "16505966592"
                os: Windows-10-10.0.26200-SP0
                program: -m src.sweep
                python: CPython 3.10.20
                root: C:\Users\matth\Autonomous-systems-Portfolio\Portfolio 2
                startedAt: "2026-05-13T23:54:04.243482Z"
                writerId: v79d8dso9xzjm0vm7oo3927n6p957rdk
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.10.20
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
batch_size:
    value: 32
epsilon_decay:
    value: 0.99
gamma:
    value: 0.999
hidden_size:
    value: 32
lr:
    value: 0.001
