_wandb:
    value:
        cli_version: 0.26.1
        e:
            1e6oudkrxsfjzc2vn448lpg9hten5z8d:
                email: matthias@devreede.net
                executable: C:\Users\matt\miniconda3\envs\trackmania\python.exe
                git:
                    commit: 3131cf14f2a9b2d850d2b08c0406474013e03b7c
                    remote: https://github.com/Tizianovdzwet/Autonomous-systems-Portfolio.git
                host: DESKTOP-V93H26C
                os: Windows-10-10.0.19045-SP0
                program: -m src.sweep_3
                python: CPython 3.10.20
                root: C:\Users\matt\Documents\[1] - Code Projects\[0] - College\Autonomous-systems-Portfolio\Portfolio 2
                startedAt: "2026-05-16T21:02:43.194031Z"
                writerId: 1e6oudkrxsfjzc2vn448lpg9hten5z8d
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.10.20
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
action_space:
    value: 4_brake
